version: '3.8'

services:
  db:
    build: .
    container_name: football_postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PWD}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - football_app_network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PWD}
    ports:
      - "5050:80"
    networks:
      - football_app_network

networks:
  football_app_network:
    name: football_app_network
    driver: bridge
