# Generated by Django 4.2.24 on 2025-09-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 2023/2024', max_length=20, unique=True)),
                ('start_year', models.PositiveIntegerField(help_text='Starting year of the season')),
                ('end_year', models.PositiveIntegerField(help_text='Ending year of the season')),
                ('start_date', models.DateField(help_text='Season start date')),
                ('end_date', models.DateField(help_text='Season end date')),
                ('is_current', models.BooleanField(default=False, help_text='Is this the current active season?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this season available for predictions?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_year'],
                'unique_together': {('start_year', 'end_year')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='matchresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='football_app.season'),
        ),
        migrations.AlterUniqueTogether(
            name='matchresult',
            unique_together={('home_team', 'away_team', 'match_date', 'season')},
        ),
    ]
